-- 코드를 입력하세요
SELECT a.AUTHOR_ID, b.AUTHOR_NAME, a.CATEGORY, SUM(c.SALES * a.PRICE) AS TOTAL_SALES
FROM BOOK as a INNER JOIN AUTHOR AS b ON b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES AS c ON c.BOOK_ID = a.BOOK_ID
WHERE YEAR(c.SALES_DATE) = 2022 and MONTH(c.SALES_DATE) = 1
GROUP BY b.AUTHOR_NAME, a.CATEGORY
ORDER BY a.AUTHOR_ID ASC, a.CATEGORY DESC;