-- 코드를 입력하세요
SELECT YEAR, MONTH, COUNT(*) AS PURCHASED_USERS, ROUND((COUNT(*)/(SELECT COUNT(*)
     FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) AS PURCHASED_RATIO
     FROM (
     SELECT DISTINCT YEAR(O.SALES_DATE) AS YEAR, MONTH(O.SALES_DATE) AS MONTH, U.USER_ID
     FROM ONLINE_SALE O
     JOIN USER_INFO U ON O.USER_ID = U.USER_ID AND YEAR(JOINED) = 2021) A
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;