-- 코드를 입력하세요
WITH RECURSIVE TMP AS(
    SELECT 0 AS h
    UNION ALL
    SELECT h+1 FROM TMP WHERE h < 23)

SELECT h, COUNT(ANIMAL_ID) AS COUNT
FROM TMP
    LEFT OUTER JOIN ANIMAL_OUTS ON HOUR(DATETIME) = TMP.h
GROUP BY h
ORDER BY h;
